# Generated by Django 5.2.14 on 2026-05-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='core.commande')),
            ],
        ),
    ]
